export interface IFootballPlayerInfo {
    added: string;
    assists: number;
    bonus: number;
    bps: number;
    chance_of_playing_next_round: number;
    chance_of_playing_this_round: number;
    clean_sheets: number;
    code: number;
    corners_and_indirect_freekicks_order: string | null;
    corners_and_indirect_freekicks_text: string;
    creativity: string;
    creativity_rank: number;
    creativity_rank_type: number;
    direct_freekicks_order: string | null;
    direct_freekicks_text: string;
    draft_rank: number;
    dreamteam_count: number;
    element_type: number;
    ep_next: string | null;
    ep_this: string | null;
    event_points: number;
    expected_assists: string;
    expected_goal_involvements: string;
    expected_goals: string;
    expected_goals_conceded: string;
    first_name: string;
    form: string;
    form_rank: number | null;
    form_rank_type: number | null;
    goals_conceded: number;
    goals_scored: number;
    ict_index: string;
    ict_index_rank: number;
    ict_index_rank_type: number;
    id: number;
    in_dreamteam: boolean;
    influence: string;
    influence_rank: number;
    influence_rank_type: number;
    minutes: number;
    news: string;
    news_added: string;
    news_return: string | null;
    news_updated: string | null;
    own_goals: number;
    penalties_missed: number;
    penalties_order: string | null;
    penalties_saved: number;
    penalties_text: string;
    points_per_game: string;
    points_per_game_rank: number | null;
    points_per_game_rank_type: number | null;
    red_cards: number;
    saves: number;
    second_name: string;
    squad_number: number | null;
    starts: number;
    status: string;
    team: number;
    threat: string;
    threat_rank: number;
    threat_rank_type: number;
    total_points: number;
    web_name: string;
    yellow_cards: number;
}
